// <auto-generated />
namespace CLUB_VALERO_DB.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class A7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(A7));
        
        string IMigrationMetadata.Id
        {
            get { return "202207221105006_A7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
